// <auto-generated />
using Asp.netCoreMVCCrud1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Asp.netCoreMVCCrud1.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20191014120942_ComplexDataModel")]
    partial class ComplexDataModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Asp.netCoreMVCCrud1.Models.Industry", b =>
                {
                    b.Property<int>("IndustryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IndustryDescription");

                    b.Property<string>("IndustryName");

                    b.Property<int>("SectorId");

                    b.HasKey("IndustryId");

                    b.HasIndex("SectorId");

                    b.ToTable("Industries");
                });

            modelBuilder.Entity("Asp.netCoreMVCCrud1.Models.Organization", b =>
                {
                    b.Property<int>("OrganizationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OrganizationName");

                    b.Property<int>("OrganizationType");

                    b.HasKey("OrganizationId");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("Asp.netCoreMVCCrud1.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArticleDate");

                    b.Property<string>("ArticleDescription");

                    b.Property<string>("ArticleHeadline")
                        .IsRequired();

                    b.Property<string>("ArticleUrl");

                    b.Property<string>("Confidentiality");

                    b.Property<string>("Country");

                    b.Property<int>("IndustryId");

                    b.Property<string>("Maturity");

                    b.Property<int>("OrganizationId");

                    b.Property<string>("TechnicalVendor");

                    b.Property<int>("UseCaseId");

                    b.HasKey("ProjectId");

                    b.HasIndex("IndustryId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("UseCaseId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Asp.netCoreMVCCrud1.Models.Sector", b =>
                {
                    b.Property<int>("SectorId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SectorName");

                    b.HasKey("SectorId");

                    b.ToTable("Sectors");
                });

            modelBuilder.Entity("Asp.netCoreMVCCrud1.Models.Usecase", b =>
                {
                    b.Property<int>("UsecaseId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("UsecaseName");

                    b.HasKey("UsecaseId");

                    b.ToTable("Usecases");
                });

            modelBuilder.Entity("Asp.netCoreMVCCrud1.Models.Industry", b =>
                {
                    b.HasOne("Asp.netCoreMVCCrud1.Models.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Asp.netCoreMVCCrud1.Models.Project", b =>
                {
                    b.HasOne("Asp.netCoreMVCCrud1.Models.Industry", "Industry")
                        .WithMany()
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Asp.netCoreMVCCrud1.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Asp.netCoreMVCCrud1.Models.Usecase", "Usecase")
                        .WithMany()
                        .HasForeignKey("UseCaseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
